// ignore: file_names
import 'package:firebase_auth/firebase_auth.dart' as auth;
import 'UserModule.dart';

class AuthService {
  final auth.FirebaseAuth _firebaseAuth = auth.FirebaseAuth.instance;

  // ignore: unused_element
  //User auth form generated by Firbase..
  User? _userFromFirebase(auth.User? user) {
    // ignore: unnecessary_null_comparison
    if (user == null) {
      return null;
    }
    return User(user.email, user.uid);
  }
//Stream for authStatechange
  Stream<User?>? get user {
    return _firebaseAuth.authStateChanges().map(_userFromFirebase);
  }
//Sigin with email and password call
  Future<User?> signInWithEmailAndPassword(
    var email,
    String password,
  ) async {
    final credential = await _firebaseAuth.signInWithEmailAndPassword(
        email: email, password: password);
        //when user is added get the credentials
    return _userFromFirebase(credential.user);
  }
//Create user data
  Future<User?> createUserWithEmailAndPassword(
    var email,
    String password,
  ) async {
    final credential = await _firebaseAuth.createUserWithEmailAndPassword(
        email: email, password: password);
    return _userFromFirebase(credential.user);
  }
//Signout process
  Future<void> signOut() async {
    return await _firebaseAuth.signOut();
  }
}